---
title: "Report SWEETVIZ and Pandas-Profile"
output:
  html_document:
    df_print: paged
    toc: true
    theme: null
editor_options:
  chunk_output_type: inline
---
\newpage


```{r set-options, echo=FALSE, cache=FALSE}
options(width = 600)
```


# Pandas Profiling


```{python, echo=FALSE,  results='hide' ,message=FALSE}
import os
import glob

files = glob.glob('./*.html')
for f in files:
    os.remove(f)


import sys

#!python -m pip install -U pandas-profiling[notebook]
#!jupyter nbextension enable --py widgetsnbextension

# Standard Library Imports
from pathlib import Path

# Installed packages
import pandas as pd
from ipywidgets import widgets

# Our package
from pandas_profiling import ProfileReport
from pandas_profiling.utils.cache import cache_file


# Read the Titanic Dataset
file_name = cache_file(
    "titanic.csv",
    "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv",
)
df = pd.read_csv(file_name)

# Generate the Profiling Report
profile = ProfileReport(
    df, title="Titanic Dataset", html={"style": {"full_width": True}}, sort=None 
)

profile.to_file("Pandas_Profiling.html")
```


```{r  showChoro1, echo=FALSE}
shiny::includeHTML("./Pandas_Profiling.html")

```





\newpage

# Deepchecks report
```{python, echo=FALSE,  results='hide' ,message=FALSE}

import numpy as np
# General imports
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from deepchecks.tabular.datasets.classification import iris

# Load Data
iris_df = iris.load_data(data_format='Dataframe', as_train_test=False)
label_col = 'target'
df_train, df_test = train_test_split(iris_df, stratify=iris_df[label_col], random_state=0)

# Train Model
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(df_train.drop(label_col, axis=1), df_train[label_col]);

from deepchecks.tabular import Dataset

# We explicitly state that this dataset has no categorical features, otherwise they will be automatically inferred
# If the dataset has categorical features, the best practice is to pass a list with their names

ds_train = Dataset(df_train, label=label_col, cat_features=[])
ds_test =  Dataset(df_test,  label=label_col, cat_features=[])


from deepchecks.tabular.suites import full_suite

suite = full_suite()

suite.run(train_dataset=ds_train, test_dataset=ds_test, model=rf_clf).save_as_html("Deep_check")

```


```{r showChoro2 , echo=FALSE}
shiny::includeHTML("./Deep_check.html")
```




\newpage

# SWEETVIZ REPORT 

```{python , echo=FALSE,  results='hide'  ,message=FALSE}
from IPython.display import display, HTML, Image

import sweetviz as sv
import pandas as pd
train_df = pd.read_csv('http://cooltiming.com/SV/train.csv')
test_df = pd.read_csv('http://cooltiming.com/SV/test.csv')

comparison_report = sv.compare([train_df,'Train'], [test_df,'Test'], target_feat='Survived')

#comparison_report.show_notebook(layout='vertical', w=800, h=300, scale=1) 
comparison_report.show_html(layout='vertical', scale=1 , open_browser=False,
                                filepath='SWEETVIZ_REPORT.html') 

```


```{r showChoro3 , echo=FALSE}
shiny::includeHTML("./SWEETVIZ_REPORT.html")
```
