---
title: "R Notebook"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

\newpage

# Pandas Profiling


```{python, echo=FALSE,  results='hide' ,message=FALSE}
import os
import glob

files = glob.glob('./report/*.html')
for f in files:
    os.remove(f)



# Make sure that we have the latest version of pandas-profiling.

# In[12]:


import sys



# !python -m pip install ipywidgets -y
# !conda install -c conda-forge pyyaml -y


# You might want to restart the kernel now.



# Standard Library Imports
from pathlib import Path

# Installed packages
import pandas as pd

# Our package
from pandas_profiling import ProfileReport
from pandas_profiling.utils.cache import cache_file




# Read the Titanic Dataset

df = pd.read_csv("./data/titanic.csv")
df.head()


# Generate the Profiling Report
profile = ProfileReport(    df, title="Titanic Dataset", html={"style": {"full_width": True}}, sort=None)




# Or use the HTML report in an iframe
# profile


# !mkdir report




profile.to_file("./report/ProfileReport.html" )


```


```{r  showChoro1, echo=FALSE}
shiny::includeHTML("./report/ProfileReport.html")
```
\newpage

# Deepchecks report
```{python, echo=FALSE,  results='hide' ,message=FALSE}

import numpy as np
# General imports
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

from deepchecks.tabular.datasets.classification import iris

# Load Data
iris_df = iris.load_data(data_format='Dataframe', as_train_test=False)
label_col = 'target'
df_train, df_test = train_test_split(iris_df, stratify=iris_df[label_col], random_state=0)

# Train Model
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(df_train.drop(label_col, axis=1), df_train[label_col]);

from deepchecks.tabular import Dataset

# We explicitly state that this dataset has no categorical features, otherwise they will be automatically inferred
# If the dataset has categorical features, the best practice is to pass a list with their names

ds_train = Dataset(df_train, label=label_col, cat_features=[])
ds_test =  Dataset(df_test,  label=label_col, cat_features=[])


from deepchecks.tabular.suites import full_suite

suite = full_suite()

suite.run(train_dataset=ds_train, test_dataset=ds_test, model=rf_clf).save_as_html("./report/Deep_check.html")

```


```{r showChoro2 , echo=FALSE}
shiny::includeHTML("./report/Deep_check.html")
```
\newpage

# SWEETVIZ REPORT 

```{python , echo=FALSE,  results='hide'  ,message=FALSE}

import sweetviz as sv
import pandas as pd
from sklearn.model_selection import train_test_split
data = pd.read_csv('../data/titanic.csv')
train_df, test_df = train_test_split(data, test_size=0.20)

# Step 1: Generate the report
# We are giving names to each dataset (optional), and specifying a target feature (optional also)
# Specifying a target feature is extremely valuable as it will show how "Survived" is affected by each variable
comparison_report = sv.compare([train_df,'Train'], [test_df,'Test'], target_feat='Survived')

comparison_report.show_html(  filepath='./report/SWEETVIZ_REPORT.html', 
            open_browser=False, 
            layout='vertical', # layout='widescreen'
            scale=1)

```


```{r  showChoro3, echo=FALSE}
shiny::includeHTML("./report/SWEETVIZ_REPORT.html")
```
